"""empty message

Revision ID: a3259bc19774
Revises: 428358964643
Create Date: 2024-08-06 17:30:02.769926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3259bc19774'
down_revision = '428358964643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_name', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('nick_name', sa.String(length=100), nullable=True),
    sa.Column('dog_age', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('dog_sex', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('account_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked_user_id', sa.Integer(), nullable=False),
    sa.Column('match_likes', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('likes')
    op.drop_table('user_account')
    # ### end Alembic commands ###
