"""empty message

Revision ID: acdb3f08ec27
Revises: b150df4473e5
Create Date: 2024-08-20 12:26:15.824217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acdb3f08ec27'
down_revision = 'b150df4473e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_account', ['user_id'], ['user_id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_account', ['user_id'], ['user_id'])

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traits', sa.String(length=250), nullable=False))
        batch_op.drop_column('nick_name')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nick_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('traits')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
